version: "3"
services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=my_cool_secret
      - MARIADB_ROOT_PASSWORD=sinensia
      - MARIADB_DATABASE=wordpress
#    ports:
#       - "3306:3306"
    volumes:
       - ./mariadb-data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: example-user
      WORDPRESS_DB_PASSWORD: my_cool_secret
      WORDPRESS_DB_NAME: wordpress
    ports:
       - "80:80"
    volumes:
       - ./htdocs:/var/www/html
