version: "3"
services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=my_cool_secret
      - MARIADB_ROOT_PASSWORD=sinensia
      - MARIADB_DATABASE=wordpress
    ports:
       - "3306:3306"
       - "80:80"
    volumes:
       - ./mariadb-data:/var/lib/mysql

  apache:
    image: httpd:latest
    ports:
       - "80:80"
    volumes:
       - ./htdocs:/usr/local/apache2/htdocs
